# Generated by Django 4.2.7 on 2023-11-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0004_usertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
