# Generated by Django 4.2.7 on 2023-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0005_alter_userform_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
