# Generated by Django 4.2.7 on 2023-11-16 03:24

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0006_alter_usertest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desriptions', models.TextField()),
                ('image', models.ImageField(upload_to='media/courses/image')),
                ('languages', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acdemiy.coursescategory', verbose_name='')),
            ],
            options={
                'verbose_name': 'CoursesModel',
                'verbose_name_plural': 'CoursesModels',
            },
        ),
        migrations.CreateModel(
            name='UserCoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('created', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acdemiy.coursesmodel', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acdemiy.userform', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='CoursDetailesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/courses_detail/image')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('for_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acdemiy.coursesmodel', verbose_name='')),
            ],
            options={
                'verbose_name': 'CoursDetailesListModel',
                'verbose_name_plural': 'CoursDetailesListModels',
            },
        ),
    ]
