# Generated by Django 4.2.7 on 2023-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0007_coursescategory_coursesmodel_usercoursesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
