# Generated by Django 4.2.7 on 2023-11-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0008_coursesmodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursdetaileslistmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
