# Generated by Django 4.2.7 on 2023-11-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0009_alter_coursdetaileslistmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursesmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
