# Generated by Django 4.2.7 on 2023-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdemiy', '0012_forum_model_comments_forum_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
